pb_camion_homepage:
    path:     /
    defaults: { _controller: PBCamionBundle:Camion:index }

pb_camion_addcamion:
  path: loc/add/
  defaults:
    _controller: PBCamionBundle:Camion:addCamion

pb_camion_viewcamion:
  path: loc/view/{id}/
  defaults:
    _controller: PBCamionBundle:Camion:viewCamion
    requirements:
        page: \d+

pb_camion_editcamion:
  path: loc/edit/{id}/
  defaults:
    _controller: PBCamionBundle:Camion:editCamion
    requirements:
        page: \d+

pb_camion_deletecamion:
  path: loc/delete/{id}/
  defaults:
    _controller: PBCamionBundle:Camion:deleteCamion
    requirements:
        page: \d+

pb_camion_addloueur:
  path: loueur/add/
  defaults:
    _controller: PBCamionBundle:Loueur:addLoueur

pb_camion_viewloueur:
  path: loueur/view/{id}/
  defaults:
    _controller: PBCamionBundle:Loueur:viewLoueur
    requirements:
        page: \d+

pb_camion_editloueur:
  path: loueur/edit/{id}/
  defaults:
    _controller: PBCamionBundle:Loueur:editLoueur
    requirements:
        page: \d+

pb_camion_deleteloueur:
  path: loueur/delete/{id}/
  defaults:
    _controller: PBCamionBundle:Loueur:deleteLoueur
    requirements:
        page: \d+

pb_camion_indexloueur:
  path: loueur/index
  defaults:
    _controller: PBCamionBundle:Loueur:indexLoueur
    requirements:
        page: \d+

pb_camion_viewmail:
  path: loueur/mail/view/{id}/
  defaults:
    _controller: PBCamionBundle:Camion:viewMail
    requirements:
        page: \d+

pb_camion_sendmail:
  path: loueur/mail/send/{id}/
  defaults:
    _controller: PBCamionBundle:Camion:sendMail
    requirements:
        page: \d+

pb_camion_editfacture:
  path: facture/edit/{id}
  defaults:
    _controller: PBCamionBundle:Factures:editFacture
  requirements:
    id: \d+

pb_camion_viewfactures:
  path: factures/view
  defaults:
    _controller: PBCamionBundle:Factures:viewFactures
    page: 1
    requirements:
      page: \d*

pb_camion_viewfacture:
  path: facture/view/{id}
  defaults:
    _controller: PBCamionBundle:Factures:viewFacture
    page: 1
    requirements:
      page: \d+

pb_camion_addfacture:
  path: facture/add
  defaults:
    _controller: PBCamionBundle:Factures:addFacture

pb_camion_deletefacture:
  path: facture/delete/{id}
  defaults:
    _controller: PBCamionBundle:Factures:deleteFacture
    requirements:
      page: \d+