pb_camion_homepage:
    path:     /
    defaults: { _controller: PBCamionBundle:Camion:index }

pb_camion_addcamion:
  path: add/
  defaults:
    _controller: PBCamionBundle:Camion:addCamion

pb_camion_viewcamion:
  path: view/{id}/
  defaults:
    _controller: PBCamionBundle:Camion:viewCamion
    requirements:
        page: \d+

pb_camion_editcamion:
  path: edit/{id}/
  defaults:
    _controller: PBCamionBundle:Camion:editCamion
    requirements:
        page: \d+

pb_camion_deletecamion:
  path: delete/{id}/
  defaults:
    _controller: PBCamionBundle:Camion:deleteCamion
    requirements:
        page: \d+