pb_transport_homepage:
  path: /{page}
  defaults: 
    _controller: PBTransportBundle:Transport:index
    page: 1
  requirements:
    page: \d*

pb_transport_viewtransport:
  path: view/{id}/
  defaults: 
    _controller: PBTransportBundle:Transport:viewTransport
  requirements:
    page: \d+

pb_transport_adddetailtransport:
  path: add/{id}
  defaults: 
    _controller: PBTransportBundle:Transport:addDetailTransport
  requirements:
    page: \d+

pb_transport_addtransport:
  path: add/
  defaults: 
    _controller: PBTransportBundle:Transport:addTransport

pb_transport_viewadresses:
  path: adresses/view
  defaults: 
    _controller: PBTransportBundle:Transport:viewAdresses

pb_transport_editadresse:
  path: adresse/edit/{id}/
  defaults: 
    _controller: PBTransportBundle:Transport:editAdresse
  requirements:
    page: \d+

pb_transport_edittransport:
  path: edit/{id}/
  defaults: 
    _controller: PBTransportBundle:Transport:editTransport
  requirements:
    page: \d+

pb_transport_deletetransport:
  path: delete/{id}/
  defaults: 
    _controller: PBTransportBundle:Transport:deleteTransport
  requirements:
    page: \d+

pb_transport_addcontact:
  path: contact/add
  defaults: 
    _controller: PBTransportBundle:Transport:addContact