pb_transport_homepage:
  path: /{page}/
  defaults: 
    _controller: PBTransportBundle:Transport:index
    page: 1
  requirements:
    page: \d*

pb_transport_viewtransport:
  path: viewtransport/{id}/
  defaults: 
    _controller: PBTransportBundle:Transport:viewTransport
  requirements:
    page: \d+

pb_transport_addtransport:
  path: addtransport/
  defaults: 
    _controller: PBTransportBundle:Transport:addTransport

pb_transport_viewadresses:
  path: adresses/
  defaults: 
    _controller: PBTransportBundle:Transport:viewAdresses

pb_transport_editadresse:
  path: adresse/{id}/
  defaults: 
    _controller: PBTransportBundle:Transport:editAdresse
  requirements:
    page: \d+