pb_transport_homepage:
  path: /{page}/
  defaults: 
    _controller: PBTransportBundle:Transport:index
    page: 1
  requirements:
    page: \d*

pb_transport_viewtransport:
  path: view/{id}/
  defaults: 
    _controller: PBTransportBundle:Transport:view
  requirements:
    page: \d+

pb_transport_addtransport:
  path: add/
  defaults: 
    _controller: PBTransportBundle:Transport:add