pb_transport_accueil:
  path: /{page}
  defaults: 
    _controller: PBTransportBundle:Transport:index
    page: 1
  requirements:
    page: \d*

pb_transport_homepage:
  path: /{page}
  defaults:
    _controller: PBTransportBundle:Transport:index
    page: 1
  requirements:
    page: \d*

pb_transport_viewtransport:
  path: view/{id}/
  defaults: 
    _controller: PBTransportBundle:Transport:viewTransport
  requirements:
    page: \d+

pb_transport_adddetailtransport:
  path: add/{id}
  defaults: 
    _controller: PBTransportBundle:Transport:addDetailTransport
  requirements:
    page: \d+

pb_transport_addtransport:
  path: add/
  defaults: 
    _controller: PBTransportBundle:Transport:addTransport

pb_transport_addadresse:
  path: adresse/add/
  defaults:
    _controller: PBTransportBundle:Transport:addAdresse


pb_transport_viewadresses:
  path: adresses/view
  defaults: 
    _controller: PBTransportBundle:Transport:viewAdresses

pb_transport_editadresse:
  path: adresse/edit/{id}/
  defaults: 
    _controller: PBTransportBundle:Transport:editAdresse
  requirements:
    page: \d+

pb_transport_edittransport:
  path: edit/{id}/
  defaults: 
    _controller: PBTransportBundle:Transport:editTransport
  requirements:
    page: \d+

pb_transport_deletetransport:
  path: delete/{id}/
  defaults: 
    _controller: PBTransportBundle:Transport:deleteTransport
  requirements:
    page: \d+

pb_transport_addcontact:
  path: contact/add
  defaults: 
    _controller: PBTransportBundle:Transport:addContact

pb_transport_editcontact:
  path: contact/edit/{id}
  defaults:
    _controller: PBTransportBundle:Transport:editContact
    requirements:
      id: \d+

pb_transport_viewcontacts:
  path: contact/view
  defaults:
    _controller: PBTransportBundle:Transport:viewContacts

pb_transport_viewcontact:
  path: contact/view/{id}
  defaults:
    _controller: PBTransportBundle:Transport:viewContact
    requirements:
      id: \d+

pb_transport_deletecontact:
  path: contact/delete/{id}
  defaults:
    _controller: PBTransportBundle:Transport:deleteContact
  requirements:
    id: \d+

pb_transport_addtransporteur:
  path: transporteur/add
  defaults:
    _controller: PBTransportBundle:Transport:addTransporteur

pb_transport_edittransporteur:
  path: transporteur/edit/{id}
  defaults:
    _controller: PBTransportBundle:Transport:editTransporteur
    requirements:
      id: \d+

pb_transport_viewtransporteurs:
  path: transporteur/view
  defaults:
    _controller: PBTransportBundle:Transport:viewTransporteurs

pb_transport_viewtransporteur:
  path: transporteur/view/{id}
  defaults:
    _controller: PBTransportBundle:Transport:viewTransporteur
    requirements:
      id: \d+

pb_transport_deletetransporteur:
  path: transporteur/delete/{id}
  defaults:
    _controller: PBTransportBundle:Transport:deleteTransporteur
  requirements:
    id: \d+

pb_transport_deleteadresse:
  path: adresse/delete/{id}
  defaults:
    _controller: PBTransportBundle:Transport:deleteAdresse
  requirements:
    id: \d+

pb_transport_editfacture:
  path: facture/edit/{id}
  defaults:
    _controller: PBTransportBundle:Transport:editFacture
  requirements:
    id: \d+

pb_transport_viewfactures:
  path: factures/view/{page}
  defaults:
    _controller: PBTransportBundle:Transport:viewFactures
    page: 1
    requirements:
      page: \d*

pb_transport_viewfacture:
  path: facture/view/{id}
  defaults:
    _controller: PBTransportBundle:Transport:viewFacture
    page: 1
    requirements:
      page: \d+

pb_transport_addfacture:
  path: facture/add
  defaults:
    _controller: PBTransportBundle:Transport:addFacture

pb_transport_deletefacture:
  path: facture/delete/{id}
  defaults:
    _controller: PBTransportBundle:Transport:deleteFacture
    requirements:
      page: \d+