<?php

namespace PB\TransportBundle\Repository;
use Doctrine\ORM\QueryBuilder;

/**
 * AdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAdresses()
	{
		return $query = $this -> createQueryBuilder('a')
			-> leftJoin('a.contacts', 'c')
			-> addSelect('c')
			-> orderBy('a.societe')
			-> getQuery()
			-> getResult();
	}

}

