<?php

namespace PB\TransportBundle\Repository;

/**
 * FacturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturesRepository extends \Doctrine\ORM\EntityRepository
{
}
