<?php

namespace PB\TransportBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * FacturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $page
     * @param $nbPerPage
     * @return Paginator
     */
    public function getFactures($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('f')
            ->orderBy('f.id', 'DESC')
            ->getQuery()
        ;

        $query
            ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage)
        ;

        return new Paginator($query, true);
    }
}
