<?php

namespace PB\TransportBundle\Repository;

/**
 * TransporteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransporteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTransporteurs()
    {
        $qb = $this ->createQueryBuilder('t')
            -> orderBy('t.nom');
        return $qb -> getQuery()->getResult();
    }
}
