<?php

namespace PB\TransportBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTransports($page, $nbPerPage)
	{
		$query = $this->createQueryBuilder('t')
		  // ->leftJoin('t.transporteur', 'tr')
		  // ->addSelect('tr')
		  // ->leftJoin('t.adresseFrom', 'af')
		  // ->addSelect('af')
		  // ->leftJoin('t.adresseTo', 'at')
		  // ->addSelect('at')		 
		  ->orderBy('t.id', 'DESC')
		  ->getQuery()
		;

		$query
		  // On définit l'annonce à partir de laquelle commencer la liste
		  ->setFirstResult(($page-1) * $nbPerPage)
		  // Ainsi que le nombre d'annonce à afficher sur une page
		  ->setMaxResults($nbPerPage)
		;

		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		return new Paginator($query, true);
	}

}
