<?php

namespace PB\TransportBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Knp\Bundle\PaginatorBundle\KnpPaginatorBundle;
use PB\TransportBundle\Entity\Transporteur;

/**
 * TransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTransports()
	{
		$query = $this->createQueryBuilder('t')
            ->leftJoin('t.transporteur', 'tr')
            ->addSelect('tr')
		  // ->leftJoin('t.adresseFrom', 'af')
		  // ->addSelect('af')
		  // ->leftJoin('t.adresseTo', 'at')
		  // ->addSelect('at')		 
		  ->orderBy('t.id', 'DESC')
		  //->getQuery()
		;

        return $query;

	}

}
