<?php

namespace PB\TransportBundle\Repository;

/**
 * typeVehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeVehiculeRepository extends \Doctrine\ORM\EntityRepository
{
}
