<?php

namespace PB\TransportBundle\Repository;

/**
 * typeTransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTransportRepository extends \Doctrine\ORM\EntityRepository
{
}
