<?php

namespace PB\CamionBundle\Repository;

/**
 * CamionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CamionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListeCamions()
    {
        $query = $this->createQueryBuilder('c')
            ->leftJoin('c.contactFrom', 'cf')
            ->addSelect('cf')
            ->orderBy('c.id', 'DESC');

        return $query;
    }
}
