<?php

namespace PB\CamionBundle\Repository;

/**
 * LoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoueurRepository extends \Doctrine\ORM\EntityRepository
{
}
